version: '3.6'
services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s

  nats:
    container_name: nats-js
    image: nats:2.9-alpine
    ports:
      - "4222:4222"
    command: "-js --http_port 8222"
    networks: ["nats"]
