version: '3.6'
services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s