apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true

  - name: Jaeger
    uid: Jaeger
    type: jaeger
    url: http://jaeger:16686/jaeger/ui
    editable: true
    isDefault: false
